FROM docker.io/library/nginx:1.27-alpine

COPY ./dashboard/nginx.conf /etc/nginx/conf.d/default.conf
COPY ./dashboard/web/ /usr/share/nginx/html/

ENTRYPOINT ["/bin/sh", "-c", "exec nginx -g 'daemon off;'"]
