apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-acl
data:
  acl.conf: |
    user default off
    user admin on >admin ~* &* +@all
    user api on >api ~* &* +LPUSH +@connection
    user worker on >worker ~* &* +BRPOP +@connection
