apiVersion: v1
kind: Secret
metadata:
  name: stratvm-secret
type: Opaque
data:
  POSTGRES_USER: c3RyYXR2bQ==
  POSTGRES_PASSWORD: c3RyYXR2bQ==
  API_REDIS_USER: YXBp
  API_REDIS_PASSWORD: YXBp
  WORKER_REDIS_USER: d29ya2Vy
  WORKER_REDIS_PASSWORD: d29ya2Vy
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stratvm-config
data:
  POSTGRES_HOST: postgres-service
  POSTGRES_PORT: "5432"
  POSTGRES_DB: stratvm
  REDIS_HOST: redis-service
  REDIS_PORT: "6379"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: stratvm
spec:
  podSelector: {}
  policyTypes:
  - Ingress
