apiVersion: v1
kind: Secret
metadata:
  name: stratvm-secret
type: Opaque
data:
  POSTGRES_USER: c3RyYXR2bQ==
  POSTGRES_PASSWORD: c3RyYXR2bQ==
  API_REDIS_USER: YXBp
  API_REDIS_PASSWORD: YXBp
  WORKER_REDIS_USER: d29ya2Vy
  WORKER_REDIS_PASSWORD: d29ya2Vy