apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      automountServiceAccountToken: false
      containers:
      - name: worker
        image: worker:latest
        imagePullPolicy: Never
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: stratvm-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: stratvm-config
              key: POSTGRES_PORT
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: stratvm-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: stratvm-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: stratvm-secret
              key: POSTGRES_PASSWORD
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: stratvm-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: stratvm-config
              key: REDIS_PORT
        - name: REDIS_USER
          valueFrom:
            secretKeyRef:
              name: stratvm-secret
              key: WORKER_REDIS_USER
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: stratvm-secret
              key: WORKER_REDIS_PASSWORD
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: worker-networkpolicy
  namespace: stratvm
spec:
  podSelector:
    matchLabels:
      app: worker
  policyTypes:
  - Ingress
  - Egress
  ingress: []
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: redis
    ports:
    - protocol: TCP
      port: 6379
  - to:
    - podSelector:
        matchLabels:
          app: postgres
    ports:
    - protocol: TCP
      port: 5432
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
