FROM ghcr.io/astral-sh/uv:0.9.18-alpine AS uv

FROM uv AS builder
WORKDIR /app

COPY shared/pyproject.toml shared/uv.lock shared/
COPY worker/pyproject.toml worker/uv.lock worker/

RUN uv sync --frozen --no-install-project

COPY shared/ ./shared/
COPY worker/ ./

RUN chown -R 65534:65534 /app/.venv

FROM uv
WORKDIR /app

COPY --from=builder /app/.venv /app/.venv
COPY --from=builder /app/shared /app/shared
COPY --from=builder /app/worker /app/worker

USER 65534

CMD ["uv", "run", "main.py"]
