FROM python:3.14-alpine

RUN pip install --no-cache-dir uv

WORKDIR /app

COPY shared/ ./shared/
COPY worker/ ./

RUN uv sync && chown -R 65534:65534 /app/.venv

USER 65534

CMD ["uv", "run", "main.py"]
