FROM ghcr.io/astral-sh/uv:0.9.18-alpine

WORKDIR /app

COPY shared/ ./shared/
COPY api/ ./

RUN uv sync && chown -R 65534:65534 /app/.venv

EXPOSE 8000

USER 65534

CMD ["uv", "run", "fastapi", "run", "--host", "0.0.0.0"]
