FROM ghcr.io/astral-sh/uv:alpine

WORKDIR /app

COPY shared/ ./shared/
COPY api/ ./

RUN uv sync && chown -R 65534:65534 /app/.venv

EXPOSE 8000

CMD ["uv", "run", "fastapi", "run", "--host", "0.0.0.0"]
