FROM ghcr.io/astral-sh/uv:0.9.18-alpine AS uv

FROM uv AS builder
WORKDIR /app

COPY shared/pyproject.toml shared/uv.lock shared/
COPY api/pyproject.toml api/uv.lock api/

RUN uv sync --frozen --no-install-project

COPY shared/ ./shared/
COPY api/ ./

RUN chown -R 65534:65534 /app/.venv

FROM uv
WORKDIR /app

COPY --from=builder /app/.venv /app/.venv
COPY --from=builder /app/shared /app/shared
COPY --from=builder /app/api /app/api

EXPOSE 8000

USER 65534

CMD ["uv", "run", "fastapi", "run", "--host", "0.0.0.0"]
