name: build

on:
  push:
    branches: [v2]

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: samyponsar

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      packages: write
    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push api
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./api/Containerfile
          outputs: type=registry
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/api:main